"""Observability: Prometheus metrics + request correlation IDs."""
from __future__ import annotations

from src.observability.metrics import (
    CONTENT_TYPE_LATEST,
    REGISTRY,
    REQUEST_ID_HEADER,
    Counter,
    Gauge,
    Histogram,
    MetricsRegistry,
    RequestIdFilter,
    RequestIDMiddleware,
    SearchTracker,
    get_request_id,
    metrics_endpoint,
    new_request_id,
    normalize_request_id,
    observe_search_latency,
    record_cache_hit,
    record_cache_miss,
    record_circuit_breaker_trip,
    record_rate_limit_throttled,
    record_search,
    register_collector,
    render_metrics,
    request_id_scope,
    reset_metrics,
    reset_request_id,
    set_browser_pool_stats,
    set_cache_stats,
    set_request_id,
    track_search,
    unregister_collector,
)

__all__ = [
    "CONTENT_TYPE_LATEST",
    "REGISTRY",
    "REQUEST_ID_HEADER",
    "Counter",
    "Gauge",
    "Histogram",
    "MetricsRegistry",
    "RequestIDMiddleware",
    "RequestIdFilter",
    "SearchTracker",
    "get_request_id",
    "metrics_endpoint",
    "new_request_id",
    "normalize_request_id",
    "observe_search_latency",
    "record_cache_hit",
    "record_cache_miss",
    "record_circuit_breaker_trip",
    "record_rate_limit_throttled",
    "record_search",
    "register_collector",
    "render_metrics",
    "request_id_scope",
    "reset_metrics",
    "reset_request_id",
    "set_browser_pool_stats",
    "set_cache_stats",
    "set_request_id",
    "track_search",
    "unregister_collector",
]
